#############################################################################
# Makefile for building: pure-qml
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  pure-qml.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile pure-qml.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_VIRTUALKEYBOARD_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -fno-exceptions -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -fno-exceptions -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtVirtualKeyboard -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pure-qml1.0.0
DISTDIR = /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/.obj/pure-qml1.0.0
LINK          = g++
LFLAGS        = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -Wl,-O1 -Wl,--enable-new-dtags
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5VirtualKeyboard.so /usr/lib/x86_64-linux-gnu/libQt5Quick.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = main.cpp .rcc/qrc_pure-qml.cpp
OBJECTS       = .obj/main.o \
		.obj/qrc_pure-qml.o
DIST          = ../../../mkspecs/modules-inst/qt_lib_waylandclient.pri \
		../../../mkspecs/modules-inst/qt_lib_waylandclient_private.pri \
		../../../mkspecs/modules/qt_lib_waylandclient.pri \
		../../../mkspecs/modules-inst/qt_lib_waylandcompositor.pri \
		../../../mkspecs/modules-inst/qt_lib_waylandcompositor_private.pri \
		../../../mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../mkspecs/modules-inst/qt_plugin_bradient.pri \
		../../../mkspecs/modules/qt_plugin_bradient.pri \
		../../../mkspecs/modules-inst/qt_plugin_drm-egl-server.pri \
		../../../mkspecs/modules/qt_plugin_drm-egl-server.pri \
		../../../mkspecs/modules-inst/qt_plugin_ivi-shell.pri \
		../../../mkspecs/modules/qt_plugin_ivi-shell.pri \
		../../../mkspecs/modules-inst/qt_plugin_qt-plugin-wayland-egl.pri \
		../../../mkspecs/modules/qt_plugin_qt-plugin-wayland-egl.pri \
		../../../mkspecs/modules-inst/qt_plugin_qwayland-egl.pri \
		../../../mkspecs/modules/qt_plugin_qwayland-egl.pri \
		../../../mkspecs/modules-inst/qt_plugin_qwayland-generic.pri \
		../../../mkspecs/modules/qt_plugin_qwayland-generic.pri \
		../../../mkspecs/modules-inst/qt_plugin_shm-emulation-server.pri \
		../../../mkspecs/modules/qt_plugin_shm-emulation-server.pri \
		../../../mkspecs/modules-inst/qt_plugin_wayland-eglstream-controller.pri \
		../../../mkspecs/modules/qt_plugin_wayland-eglstream-controller.pri \
		../../../mkspecs/modules-inst/qt_plugin_wl-shell.pri \
		../../../mkspecs/modules/qt_plugin_wl-shell.pri \
		../../../mkspecs/modules-inst/qt_plugin_xdg-shell-v5.pri \
		../../../mkspecs/modules/qt_plugin_xdg-shell-v5.pri \
		../../../mkspecs/modules-inst/qt_plugin_xdg-shell-v6.pri \
		../../../mkspecs/modules/qt_plugin_xdg-shell-v6.pri \
		../../../mkspecs/modules-inst/qt_plugin_xdg-shell.pri \
		../../../mkspecs/modules/qt_plugin_xdg-shell.pri \
		../../../mkspecs/modules/qt_tool_qtwaylandscanner.pri \
		../../../.qmake.conf \
		../../../.qmake.stash \
		pure-qml.pro  main.cpp
QMAKE_TARGET  = pure-qml
DESTDIR       = 
TARGET        = pure-qml


first: all
####### Build rules

pure-qml:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pure-qml.pro ../../../.qmake.conf ../../../.qmake.cache /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../mkspecs/modules-inst/qt_lib_waylandclient.pri \
		../../../mkspecs/modules-inst/qt_lib_waylandclient_private.pri \
		../../../mkspecs/modules/qt_lib_waylandclient.pri \
		../../../mkspecs/modules-inst/qt_lib_waylandcompositor.pri \
		../../../mkspecs/modules-inst/qt_lib_waylandcompositor_private.pri \
		../../../mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../mkspecs/modules-inst/qt_plugin_bradient.pri \
		../../../mkspecs/modules/qt_plugin_bradient.pri \
		../../../mkspecs/modules-inst/qt_plugin_drm-egl-server.pri \
		../../../mkspecs/modules/qt_plugin_drm-egl-server.pri \
		../../../mkspecs/modules-inst/qt_plugin_ivi-shell.pri \
		../../../mkspecs/modules/qt_plugin_ivi-shell.pri \
		../../../mkspecs/modules-inst/qt_plugin_qt-plugin-wayland-egl.pri \
		../../../mkspecs/modules/qt_plugin_qt-plugin-wayland-egl.pri \
		../../../mkspecs/modules-inst/qt_plugin_qwayland-egl.pri \
		../../../mkspecs/modules/qt_plugin_qwayland-egl.pri \
		../../../mkspecs/modules-inst/qt_plugin_qwayland-generic.pri \
		../../../mkspecs/modules/qt_plugin_qwayland-generic.pri \
		../../../mkspecs/modules-inst/qt_plugin_shm-emulation-server.pri \
		../../../mkspecs/modules/qt_plugin_shm-emulation-server.pri \
		../../../mkspecs/modules-inst/qt_plugin_wayland-eglstream-controller.pri \
		../../../mkspecs/modules/qt_plugin_wayland-eglstream-controller.pri \
		../../../mkspecs/modules-inst/qt_plugin_wl-shell.pri \
		../../../mkspecs/modules/qt_plugin_wl-shell.pri \
		../../../mkspecs/modules-inst/qt_plugin_xdg-shell-v5.pri \
		../../../mkspecs/modules/qt_plugin_xdg-shell-v5.pri \
		../../../mkspecs/modules-inst/qt_plugin_xdg-shell-v6.pri \
		../../../mkspecs/modules/qt_plugin_xdg-shell-v6.pri \
		../../../mkspecs/modules-inst/qt_plugin_xdg-shell.pri \
		../../../mkspecs/modules/qt_plugin_xdg-shell.pri \
		../../../mkspecs/modules/qt_tool_qtwaylandscanner.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qmodule.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_prefix_build_check.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_build_config.prf \
		../../../.qmake.conf \
		../../../.qmake.cache \
		../../../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions_off.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_example_installs.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_docs_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/largefile.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_build_extra.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		pure-qml.pro \
		pure-qml.qrc
	$(QMAKE) -o Makefile pure-qml.pro -spec linux-g++
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../../mkspecs/modules-inst/qt_lib_waylandclient.pri:
../../../mkspecs/modules-inst/qt_lib_waylandclient_private.pri:
../../../mkspecs/modules/qt_lib_waylandclient.pri:
../../../mkspecs/modules-inst/qt_lib_waylandcompositor.pri:
../../../mkspecs/modules-inst/qt_lib_waylandcompositor_private.pri:
../../../mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../mkspecs/modules-inst/qt_plugin_bradient.pri:
../../../mkspecs/modules/qt_plugin_bradient.pri:
../../../mkspecs/modules-inst/qt_plugin_drm-egl-server.pri:
../../../mkspecs/modules/qt_plugin_drm-egl-server.pri:
../../../mkspecs/modules-inst/qt_plugin_ivi-shell.pri:
../../../mkspecs/modules/qt_plugin_ivi-shell.pri:
../../../mkspecs/modules-inst/qt_plugin_qt-plugin-wayland-egl.pri:
../../../mkspecs/modules/qt_plugin_qt-plugin-wayland-egl.pri:
../../../mkspecs/modules-inst/qt_plugin_qwayland-egl.pri:
../../../mkspecs/modules/qt_plugin_qwayland-egl.pri:
../../../mkspecs/modules-inst/qt_plugin_qwayland-generic.pri:
../../../mkspecs/modules/qt_plugin_qwayland-generic.pri:
../../../mkspecs/modules-inst/qt_plugin_shm-emulation-server.pri:
../../../mkspecs/modules/qt_plugin_shm-emulation-server.pri:
../../../mkspecs/modules-inst/qt_plugin_wayland-eglstream-controller.pri:
../../../mkspecs/modules/qt_plugin_wayland-eglstream-controller.pri:
../../../mkspecs/modules-inst/qt_plugin_wl-shell.pri:
../../../mkspecs/modules/qt_plugin_wl-shell.pri:
../../../mkspecs/modules-inst/qt_plugin_xdg-shell-v5.pri:
../../../mkspecs/modules/qt_plugin_xdg-shell-v5.pri:
../../../mkspecs/modules-inst/qt_plugin_xdg-shell-v6.pri:
../../../mkspecs/modules/qt_plugin_xdg-shell-v6.pri:
../../../mkspecs/modules-inst/qt_plugin_xdg-shell.pri:
../../../mkspecs/modules/qt_plugin_xdg-shell.pri:
../../../mkspecs/modules/qt_tool_qtwaylandscanner.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qmodule.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_prefix_build_check.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_build_config.prf:
../../../.qmake.conf:
../../../.qmake.cache:
../../../.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions_off.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_example_installs.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_docs_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/largefile.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_build_extra.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
pure-qml.pro:
pure-qml.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile pure-qml.pro -spec linux-g++

qmake_all: FORCE


all: Makefile pure-qml

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents pure-qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

install_html_docs:

uninstall_html_docs:

install_qch_docs:

uninstall_qch_docs:

install_docs:

uninstall_docs:

qch_docs:

prepare_docs:

generate_docs:

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_no_pch_compiler_make_all:
compiler_no_pch_compiler_clean:
compiler_rcc_make_all: .rcc/qrc_pure-qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .rcc/qrc_pure-qml.cpp
.rcc/qrc_pure-qml.cpp: pure-qml.qrc \
		/usr/lib/qt5/bin/rcc \
		qml/Chrome.qml \
		qml/Screen.qml \
		qml/Keyboard.qml \
		qml/main.qml \
		images/background.jpg
	/usr/lib/qt5/bin/rcc -name pure-qml pure-qml.qrc -o .rcc/qrc_pure-qml.cpp

compiler_moc_predefs_make_all: .moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) .moc/moc_predefs.h
.moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -fno-exceptions -Wall -W -dM -E -o .moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

.obj/main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/qrc_pure-qml.o: .rcc/qrc_pure-qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qrc_pure-qml.o .rcc/qrc_pure-qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/ 


install_sources: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/main.cpp $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/main.cpp
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/pure-qml.qrc $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.qrc
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/pure-qml.pro $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.pro
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/images $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/images
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/qml $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/qml
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/pure-qml.pro $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.pro
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/main.cpp $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/main.cpp
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/pure-qml.qrc $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.qrc

uninstall_sources: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.qrc
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/main.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.pro
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/images
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.pro
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.qrc
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/main.cpp
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/ 


install_sources: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/main.cpp $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/main.cpp
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/pure-qml.qrc $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.qrc
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/pure-qml.pro $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.pro
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/images $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/images
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/qml $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/qml
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/pure-qml.pro $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.pro
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/main.cpp $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/main.cpp
	-$(QINSTALL) /home/jareas/Developer/qtwayland-everywhere-src-5.12.8/examples/wayland/pure-qml/pure-qml.qrc $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.qrc

uninstall_sources: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.qrc
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/main.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.pro
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/qml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/images
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.pro
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml.qrc
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/main.cpp
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/wayland/pure-qml/ 


install: install_target install_sources install_sources  FORCE

uninstall: uninstall_target uninstall_sources uninstall_sources  FORCE

FORCE:

